### ISSUE TITLE
Prevent Shelly device from overheating

### ISSUE THREAD

**Issue by jberrenberg** [evgeni/esphome-somfy#4]
Thanks for sharing your shelly 2.5 configurations, just a quick note. 

According to https://esphome.io/components/sensor/ade7953.html#use-with-shelly-2-5 you should set `irq_pin: GPIO16` for the the `ade7953` sensor. 
 
> Lastly, the ADE7953 IRQ line is connected to the GPIO16. The `irq_pin` MUST be set to GPIO16 to prevent device overheat (>70ºC idling).

The temperature of my shelly decreased quite a lot after applying this change.

**Comment by evgeni** [comment]
Nice, thanks for the hint!
